services:
  - type: web
    name: SAINI TXT DIRECT 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/idrivedigital/saini-txt-direct
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
